export const SystemConstant = {
  PASSWORD_REGEX: "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).+$",
  PASSWORD_INVALID:
    "Password must contain at least one uppercase and lowercase letter, one number & one special character",
  EMAIL: "email",
  REMEMBER_ME: "rememberMe",
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  ROLE: "role",
  EMAIL_REGEX: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
  COMPANY_ID: "company_id",
  COMPANY_NAME: "company_name",
  POSTAL_REGEX: "^[A-Za-z0-9](?:[A-Za-z0-9s-]{1,10}[A-Za-z0-9])?$",
  PHONE_REGEX: "^[+]?[(]?[0-9]{1,4}[)]?[-s./0-9]*$",
  COMPANY_SIZE: "companysize",
  INDUSTRY: "industry",
  TOKEN: "token",
  PAGE: "page",
  NAME: "name",
  SIGNIN: "signin",
  SIGNUP: "signup",
  PROFILE_PHOTO: "profile_photo",
  VALIDATE_TOKEN: "validate_token",
  TRUE: "true",
  FALSE: "false",
  WEEK_DAYS: "weekdays",
  MIN_ZERO: 0,
  MAX_HUNDRED: 100,
  MAX_NUMERIC_5_2: 999.99,
};
